### ISSUE TITLE
ngp-piwik directive is restrict: 'E'

### ISSUE THREAD

**Issue by traviscosgrave** [mike-spainhower/angular-piwik#15]
For support in IE8, `restrict: A` is required.

My current workaround:

    angular.module('my-piwik', ['piwik']).config(function ($provide) {
        $provide.decorator('ngpPiwikDirective',['$delegate', function ($delegate) {
            var directive      = $delegate[0];
            directive.restrict = 'EA';                    // Add attribute support for IE8
            return $delegate;
        }]);
    });

**Comment by mike-spainhower** [comment]
@traviscosgrave can you confirm that #18 will fix your issue?

**Comment by SpainTrain** [comment]
This is now on bower
