### ISSUE TITLE
Piwik is an empty object

### ISSUE THREAD

**Issue by gCurtisCT** [mike-spainhower/angular-piwik#9]
I'm working inside Salesforce.com's visualforce framework.

The instructions say to reference the file from the CDN, add an html element to your page, and then, once it's on the page, you can inject the service into your controller.

The Html element:
---

Inside the `.page` file, inside the `head` of the html I have this:

    <apex:page showHeader="true" sidebar="false" standardStylesheets="false" docType="html-5.0" StandardController="Opportunity" extensions="Opportunities">
    <html>
    <head>
        <ngp-piwik ngp-set-js-url="//[server]/piwik.js" ngp-set-tracker-url="//[server]/piwik.php" ngp-set-site-id="2"> </ngp-piwik>
    </head>

The reference:
---
Outside of (after) the html I have this

    </body>
    </html>
    <apex:includeScript value="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"/>
    <apex:includeScript value="//ajax.googleapis.com/ajax/libs/angularjs/1.3.2/angular.min.js"/>
    ...
    <apex:includeScript value="https://cdn.rawgit.com/mike-spainhower/angular-piwik/v1.2.0/dist/angular-piwik.js"/>

The service:
---
Inside of the Javascript, below the above, I have this:

    <script type="text/javascript">
    var opportunitiesApp = angular.module('opportunitiesApp', [...'piwik']);
    opportunitiesApp.service('opportunitiesService', function($q, $rootScope) {
    ...
    })
     .controller('opportunitiesController', function(Piwik,$q, $scope,$location, opportunitiesService) {
		console.log(Piwik);

But this just outputs `function Piwik() {}`, indicating that it's just an empty function that I can't use.

Am I adding the dependencies in the wrong order or something? What am I doing wrong?

After viewing the network, I can see that it's successfully getting the `angular-piwik.js` file
I'm getting a `204 no response` from the `.php` file, so maybe that's it, assuming I shouldn't be getting this.

It looks like the request that gets sent has a bunch of query parameters. It looks like this:

    https://analytics.commercialtribe.net/piwik.php?action_name=salesforce.com%20-%20Developer%20Edition&idsite=1&rec=1&r=910121&h=12&m=33&s=50&url=https%3A%2F%2Fct-4-sf.na16.visual.force.com%2Fservlet%2Fservlet.Integration%3Flid%3D066j0000002Eqjv%26ic%3D1&urlref=https%3A%2F%2Fct-4-sf.na16.visual.force.com%2Fvisualforce%2Frecsession&_id=8fbf5cc5476c7d0f&_idts=1427736319&_idvc=1&_idn=0&_refts=1427736319&_viewts=1427736319&_ref=https%3A%2F%2Fna16.salesforce.com%2F006j0000006cwYq&send_image=0&pdf=1&qt=1&realp=0&wma=0&dir=0&fla=1&java=1&gears=0&ag=1&cookie=1&res=1920x1080&gt_ms=74

Without these query parameters, I can access piwik.php just fine.

Looking on my piwik site, I can see that hits are getting logged. I just can't fill out the method

**Comment by mike-spainhower** [comment]
> Looking on my piwik site, I can see that hits are getting logged. I just can't fill out the method

That sort of sounds like it is working.   What do you mean by "fill out the method"?

What is output if you `log` one of the actual methods?  e.g.,

```js
    console.log(Piwik.setTrackerUrl);
```

**Comment by mike-spainhower** [comment]
> I'm getting a 204 no response from the .php file

This is a performance feature of piwik - https://github.com/piwik/piwik/issues/6577

**Comment by gCurtisCT** [comment]
When I do
```console.log(Piwik.setTrackerUrl)``` I get this:

    function () {
            var arg, cmd, _j, _len1;
            cmd = [method];
            for (_j = 0, _len1 = arguments.length; _j < _len1; _j++) {
              arg = arguments[_j];
              cmd.push(arg);
            }
            return $window['_paq'].push(cmd);
          }

Which seems right.

However, when I do `console.log(Piwik.getAyncTracker())` I get `undefined is not a function`, which was what I tried first, and which indicated that there was a problem.

Perhaps it was working all along, and the two `getTracker` methods are unnecessary, and thus, weren't included?

**Comment by mike-spainhower** [comment]
Well, you don't need to call `getAyncTracker` because you already have it, that's what the `Piwik` service object essentially is :smile:.  You can see the list of "action" methods here https://github.com/mike-spainhower/angular-piwik/blob/master/lib/angular-piwik.coffee#L5 and "get" methods here https://github.com/mike-spainhower/angular-piwik/blob/master/lib/angular-piwik.coffee#L50 .  If it is ever out-of-date, feel free to open an issue or PR to add the missing functionality.

**Comment by gCurtisCT** [comment]
Thanks!

I was confused by the line in the readme that read:
>The Piwik object has all the same methods as the official Piwik js tracker.

So after I hooked it up, I went here to see the methods
http://developer.piwik.org/api-reference/tracking-javascript

The first and second methods on the list were the first two things that I tried, and that was what made me think that there was a problem. Hah.

Also, I was expecting `console.log(Piwik)` to be more than just an empty function, but this was a false assumption on my part.

**Comment by mike-spainhower** [comment]
No problem.  Perhaps I will change that to say something like "The Piwik object has all the same methods as the tracker returned by `getTracker` or `getAsyncTracker` on the raw `Piwik` object."  Would phrasing like that make it more clear?


> I was expecting console.log(Piwik) to be more than just an empty function

Yes, mildly misleading, but it's what happens when you create a `class` in CoffeeScript without a `constructor`.  Not exactly a common pattern in vanilla JavaScript :grin:

**Comment by gCurtisCT** [comment]
Yes, I think that phrasing would make it more clear.
